=== Vasyl1889/XMLParser/bin/candy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:include schemaLocation=""></xsd:include>
    <xsd:annotation>
        <xsd:documentation xml:lang="en">Candy schema.
        </xsd:documentation>
    </xsd:annotation>

    <xsd:element name="candies" type="Candies"></xsd:element>
    <xsd:complexType name="Candies">
        <xsd:sequence>
            <xsd:element ref="candy" minOccurs="0" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="candy" type="CandyType"/>
    <xsd:complexType name="CandyType">
        <xsd:sequence>
            <xsd:element name="energy" type="QuantityType"/>
            <xsd:element name="type" type="TypeType"/>
            <xsd:element name="ingredients" type="IngredientsType"/>
            <xsd:element name="value" type="ValueType"/>
            <xsd:element name="production" type="xsd:string"/>
            <xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="nameAttribType"/>
    </xsd:complexType>

    <xsd:simpleType name="nameAttribType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Za-z]+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="TypeType">
        <xsd:simpleContent>
            <xsd:extension base="TypeNameType">
                <xsd:attribute name="filling" type="xsd:boolean" use="optional"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:simpleType name="TypeNameType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Chocolate"/>
            <xsd:enumeration value="Caramel"/>
            <xsd:enumeration value="Iris"/>
            <xsd:enumeration value="Chocolate with filling"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="IngredientsType">
        <xsd:sequence>
            <xsd:element name="ingredient" type="IngredientType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="IngredientType">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="quantity" type="QuantityType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="QuantityType">
        <xsd:restriction base="xsd:nonNegativeInteger">
            <xsd:maxInclusive value="10000"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="ValueType">
        <xsd:sequence>
            <xsd:element name="proteins" type="QuantityType"/>
            <xsd:element name="fats" type="QuantityType"/>
            <xsd:element name="carbohydrates" type="QuantityType"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== Vasyl1889/XMLParser/bin/candy.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="candy.xsd">
    <candy name="Duchess">
        <energy>299</energy>
        <type>Caramel</type>
        <ingredients>
            <ingredient>
                <name>Water</name>
                <quantity>115</quantity>
            </ingredient>
            <ingredient>
                <name>Salt</name>
                <quantity>1</quantity>
            </ingredient>
            <ingredient>
                <name>Sugar</name>
                <quantity>98</quantity>
            </ingredient>
        </ingredients>
        <value>
            <proteins>17</proteins>
            <fats>30</fats>
            <carbohydrates>48</carbohydrates>
        </value>
        <production>Roshen</production>
        <description>Good taste</description>
    </candy>

    <candy name="RoyalCharm">
        <energy>308</energy>
        <type filling="true">Chocolate with filling</type>
        <ingredients>
            <ingredient>
                <name>Water</name>
                <quantity>108</quantity>
            </ingredient>
            <ingredient>
                <name>Salt</name>
                <quantity>2</quantity>
            </ingredient>
            <ingredient>
                <name>Sugar</name>
                <quantity>98</quantity>
            </ingredient>
        </ingredients>
        <value>
            <proteins>5</proteins>
            <fats>35</fats>
            <carbohydrates>55</carbohydrates>
        </value>
        <production>AVK</production>
        <description>Wonderful taste</description>
    </candy>

    <candy name="DeLux">
        <energy>299</energy>
        <type filling="true">Chocolate with filling</type>
        <ingredients>
            <ingredient>
                <name>Water</name>
                <quantity>170</quantity>
            </ingredient>
            <ingredient>
                <name>Salt</name>
                <quantity>3</quantity>
            </ingredient>
            <ingredient>
                <name>Sugar</name>
                <quantity>168</quantity>
            </ingredient>
        </ingredients>
        <value>
            <proteins>7</proteins>
            <fats>27</fats>
            <carbohydrates>51</carbohydrates>
        </value>
        <production>Korona</production>
        <description>Wonderful taste</description>
    </candy>

    <candy name="Romashka">
        <energy>270</energy>
        <type filling="false">Chocolate</type>
        <ingredients>
            <ingredient>
                <name>Water</name>
                <quantity>95</quantity>
            </ingredient>
            <ingredient>
                <name>Salt</name>
                <quantity>1</quantity>
            </ingredient>
            <ingredient>
                <name>Sugar</name>
                <quantity>98</quantity>
            </ingredient>
        </ingredients>
        <value>
            <proteins>6</proteins>
            <fats>30</fats>
            <carbohydrates>52</carbohydrates>
        </value>
        <production>Svitoch</production>
        <description>Goog taste</description>
    </candy>
</candies>
